config/routes.rb
Rails.application.routes.draw do
  resources :posts

  root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all.order('created_at DESC')
  end

  def show
    set_post
  end

  def new
    @post = Post.new
  end

  def edit
    set_post
  end

  def create
    @post = Post.new(post_params)

    @post.save
    redirect_to @post
  end

  def update
    set_post

    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
    # respond_to do |format|
    #   if @post.update(post_params)
    #     format.html { redirect_to @post, notice: 'Post was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @post }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @post.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    
    redirect_to posts_path, notice: 'Post was successfully deleted.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
</head>
<body>
	<div id="sidebar">
    <div id="logo">
      <%= link_to root_path do %>
        <%= image_tag "logo.svg" %>
      <% end %>
    </div>

    <ul>
      <li class="category">Website</li>
      <li><%= link_to "Blog", root_path %></li>
      <li>About</li>
    </ul>

    <ul>
     <li class="category">Social</li>
     <li><a href="https://twitter.com/mackenziechild">Twitter</a></li>
     <li><a href="http://instagram.com/mackenziechild">Instagram</a></li>
     <li><a href="https://github.com/mackenziechild">Github</a></li>
     <li><a href="mailto:hey@mackenziechild.me">Email</a></li>
    </ul>

    <p class="sign_in">Admin Login</p>
  </div>

	<div id="main_content">
    <div id="header">
      <p>All Posts</p>
 
      <div class="buttons">
        <button class="button"><%= link_to "New Post", new_post_path %></button>
        <button class="button">Log Out</button>
      </div>
    </div>
 
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert") %>
    <% end %>
		<%= yield %>
	</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div id="post_content">
	<h1>Editing Post</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @post %> |
	<%= link_to 'Back', posts_path %>
</div>

app/views/posts/index.html.erb
<div id="page_wrapper">
	<p id="notice"><%= notice %></p>

	<h1>Welcome to my Blog</h1>

	<% @posts.each do |post| %>
	  <div class="post_wrapper">
	    <h2 class="title"><%= link_to post.title, post %></h2>
	    <h4 class="date"><%= post.created_at.strftime("%B %d, %Y") %></h4>
	    <p><%= truncate post.body %></p>
	  </div>
	<% end %>
</div>

app/views/posts/new.html.erb
<div id="page_wrapper">
	<h1>New Post</h1>

	<%= render 'form' %>

	<%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
	<h1 class="title">
	  <%= @post.title %>
	</h1>
	 
	<p class="date">
	  Submitted <%= time_ago_in_words(@post.created_at) %> Ago
	</p>
	 
	<p class="body">
	  <%= @post.body %>
	</p>

	<%= link_to 'Edit', edit_post_path(@post) %> |
	<%= link_to 'Back', posts_path %> |
	<%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
</div>